name: NodeJS JK Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Setup private JFrog NPM repository
        run: |
          npm config set _auth ${{ secrets.NPM_TOKEN }}
          npm config set registry https://rbcplatform.jfrog.io/rbcplatform/api/npm/npm-virtual
          npm config set always-auth true
          npm config list | grep 'registry'
      - name: Install NPM packages
        run: yarn
      - name: Build file
        run: yarn build
